// Package frontend embeds the built SvelteKit admin SPA.
// The build/ directory is generated by running `pnpm build` in this directory.
package frontend

import (
	"bytes"
	"crypto/sha256"
	"embed"
	"encoding/base64"
	"io"
	"io/fs"
	"net/http"
	"regexp"
)

//go:embed all:build
var buildFS embed.FS

var inlineScriptPattern = regexp.MustCompile(`(?s)<script(?:\s[^>]*)?>(.*?)</script>`)

// InlineScriptCSPHashes returns CSP hash sources for the generated SPA shell's
// inline bootstrap scripts. The hashes are derived from the exact embedded bytes
// served by Handler, so frontend rebuilds cannot silently stale the embed policy.
func InlineScriptCSPHashes() []string {
	document, err := buildFS.ReadFile("build/200.html")
	if err != nil {
		return nil
	}
	matches := inlineScriptPattern.FindAllSubmatch(document, -1)
	hashes := make([]string, 0, len(matches))
	for _, match := range matches {
		openingEnd := bytes.IndexByte(match[0], '>')
		if openingEnd < 0 || bytes.Contains(bytes.ToLower(match[0][:openingEnd]), []byte("src=")) {
			continue
		}
		digest := sha256.Sum256(match[1])
		hashes = append(hashes, "'sha256-"+base64.StdEncoding.EncodeToString(digest[:])+"'")
	}
	return hashes
}

// FaviconHandler serves the embedded favicon (build/favicon.svg) so the public
// server-rendered pages and the admin SPA share a single favicon source — change
// frontend/static/favicon.svg, rebuild, and every page updates.
func FaviconHandler() http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		f, err := buildFS.Open("build/favicon.svg")
		if err != nil {
			http.NotFound(w, r)
			return
		}
		defer f.Close()
		w.Header().Set("Content-Type", "image/svg+xml")
		w.Header().Set("Cache-Control", "public, max-age=3600")
		_, _ = io.Copy(w, f)
	})
}

// Handler returns an HTTP handler that serves the built admin SPA.
// Paths not matching a real file fall back to 200.html so that
// client-side routing works for all /admin/* subroutes.
func Handler() http.Handler {
	sub, err := fs.Sub(buildFS, "build")
	if err != nil {
		panic("frontend: fs.Sub: " + err.Error())
	}
	return &spaHandler{fs: http.FS(sub)}
}

type spaHandler struct {
	fs http.FileSystem
}

func (h *spaHandler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	f, err := h.fs.Open(r.URL.Path)
	if err == nil {
		st, statErr := f.Stat()
		f.Close() // #nosec G104 -- handle already Stat()-ed above; nothing actionable on close error
		// Treat directories as not-found so the SPA shell handles the route
		// instead of http.FileServer rendering a directory listing.
		if statErr == nil && st.IsDir() {
			err = fs.ErrNotExist
		}
	}
	if err != nil {
		r2 := *r
		r2.URL.Path = "/200.html"
		http.FileServer(h.fs).ServeHTTP(w, &r2)
		return
	}
	http.FileServer(h.fs).ServeHTTP(w, r)
}
